// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_Anti.Data;

#nullable disable

namespace WebApp_Anti.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118041007_AddManagerApprovalColumns")]
    partial class AddManagerApprovalColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp_Anti.Models.DiscardApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Approved")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MgrDfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MgrVp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MgrWarehouse")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiscardApprovals", "dbo");
                });

            modelBuilder.Entity("WebApp_Anti.Models.DiscardApprovalInput", b =>
                {
                    b.Property<string>("Approved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Asset Tag");

                    b.Property<string>("CleanedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cleaned By");

                    b.Property<string>("DepreciatedValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Depreciated Value");

                    b.Property<string>("DiscardNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Discard Notes");

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsUnderWarranty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Is Under Warranty");

                    b.Property<string>("LastCleaned")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last Cleaned");

                    b.Property<string>("LastRepaired")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last Repaired");

                    b.Property<string>("LastTested")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last Tested");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Last Updated");

                    b.Property<string>("Lost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Master ID");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PO #");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Purchase Date");

                    b.Property<string>("RepairedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Repaired By");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemUpdatedDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tested By");

                    b.Property<string>("UnitCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Updated By");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Warehouse Name");

                    b.ToTable("Discard Approval Input", "dbo");
                });

            modelBuilder.Entity("WebApp_Anti.Models.SerpProductInstance", b =>
                {
                    b.Property<string>("AssetTag")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Asset Tag");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Warehouse Name");

                    b.ToTable("SERP_PRODUCT_INSTANCES", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
